export enum MICROSERVICES {
    USERS = 'USERS_URL',
    GENRES = 'GENRES_URL',
    ARTISTS = 'ARTISTS_URL',
    BANDS = 'BANDS_URL',
    ALBUMS = 'ALBUMS_URL',
    TRACKS = 'TRACKS_URL',
    FAVOURITES = 'FAVOURITES_URL',
}
